// <auto-generated />
using AccessControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessControl.Migrations
{
    [DbContext(typeof(ControleAcessoContex))]
    [Migration("20230814215806_CriandoTabeladeAcessos")]
    partial class CriandoTabeladeAcessos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccessControl.Models.Acesso", b =>
                {
                    b.Property<int>("IdDeAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Sala")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdDeAcesso");

                    b.HasIndex("Documento");

                    b.ToTable("Acessos");
                });

            modelBuilder.Entity("AccessControl.Models.Pessoa", b =>
                {
                    b.Property<string>("Documento")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Documento");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("AccessControl.Models.Acesso", b =>
                {
                    b.HasOne("AccessControl.Models.Pessoa", "Pessoa")
                        .WithMany("Acessos")
                        .HasForeignKey("Documento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("AccessControl.Models.Pessoa", b =>
                {
                    b.Navigation("Acessos");
                });
#pragma warning restore 612, 618
        }
    }
}
